import puppeteer from "puppeteer";
import path from "node:path"; import fs from "node:fs"; import http from "node:http";
const root = "C:/Users/herna/Desktop/pokoreano - copia";
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'};
const server=http.createServer((req,res)=>{const p=path.join(root,decodeURIComponent(req.url.split("?")[0]==="/"?"/index.html":req.url.split("?")[0]));fs.readFile(p,(e,d)=>{if(e){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'});res.end(d);});});
await new Promise(r=>server.listen(8112,r));
const b=await puppeteer.launch({headless:"new"});
const pg=await b.newPage(); await pg.setViewport({width:1280,height:800});
pg.on("dialog",d=>d.accept());
pg.on("pageerror",e=>console.log("[pageerror]",e.message));
pg.on("console",m=>{if(m.type()==="error")console.log("[console]",m.text());});
await pg.goto("http://localhost:8112/index.html",{waitUntil:"load"});
await pg.click('[data-action="new-game"]');
await pg.waitForFunction('typeof World!=="undefined" && World.debug().ready',{timeout:20000});
await pg.evaluate(()=>World.debugEnter("home"));
await new Promise(r=>setTimeout(r,2500));
await pg.screenshot({path: path.join(root,"test-shots/home.png")});
console.log("modo:", await pg.evaluate(()=>World.debug().mode));
await b.close(); server.close();
